title: "Nguyen Ngoc Minh Chau"
email: ngocminhchau@unist.ac.kr
description: "UNIST-Ulsan National Institute of Science & Technology"
lang: "en"
date_format: "%B %d,%Y"


baseurl: "/"
url: "https://ChauNguyen.github.io/"
sass:
sass_dir: _sass

